### ISSUE TITLE
Auto-lock feature applies to admins when no role is specified

### ISSUE THREAD

**Issue by pbchase** [ctsit/linear_data_entry_workflow#35]
Auto-lock feature applies to admins when no role is specified. Specifying a dummy, empty role is sufficient to turn this unwanted behavior off.  I tested this with table-based authentication.

**Comment by ChemiKyle** [comment]
This bug still occurs in REDCap 9.8.4, though I do not recall running into it in August 2019. However, I could imagine it occurring due to either REDCap version or a PHP version.

These lines are responsible:  
https://github.com/ctsit/linear_data_entry_workflow/blob/f76ea7c1be043f1e45f30a30872a275da6bf60c4/ExternalModule.php#L298-L301

As an admin in REDCap 9.8.4, `$user_rights['role_id'] == ""`, with no `auto-locked-roles` defined in the configuration, `$roles_to_lock == null`. Strangely, although `in_array("", null)` evaluates as false and issues a warning (using PHP 7.3.11 in interactive shell mode `php -a`), my php debugger shows this evaluating as true and fires `includeJS`; indeed looking at the browser debugger, `auto-lock.js` is loaded.

**Comment by pbchase** [comment]
Addressed by PR #47
